spring:
  application:
    name: upload
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dfq?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root.
    hikari:
      minimum-idle: 5
      maximum-pool-size: 100
      idle-timeout: 30000
      validation-timeout: 250
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      #单次请求最大5MB
      max-file-size: 5MB
      #总10MB
      max-request-size: 10MB
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

server:
  port: 8082
#log
logging:
  file:
    path: /project/upload/log
#    path: ./log
upload:
  address: /project/upload/data
#  address: E:\java-IDEA\upload\place

