package com.itdfq.upload.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table upload
 */
public class Upload {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   文件名字
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   UUID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     * Database Column Remarks:
     *   文件大小
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload.size
     *
     * @mbg.generated
     */
    private Integer size;

    /**
     * Database Column Remarks:
     *   文件类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     * Database Column Remarks:
     *   文件保存地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload.save_address
     *
     * @mbg.generated
     */
    private String saveAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload.add_time
     *
     * @mbg.generated
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload.deleted_id
     *
     * @mbg.generated
     */
    private Integer deletedId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload.id
     *
     * @return the value of upload.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload.id
     *
     * @param id the value for upload.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload.name
     *
     * @return the value of upload.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload.name
     *
     * @param name the value for upload.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload.code
     *
     * @return the value of upload.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload.code
     *
     * @param code the value for upload.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload.size
     *
     * @return the value of upload.size
     *
     * @mbg.generated
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload.size
     *
     * @param size the value for upload.size
     *
     * @mbg.generated
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload.type
     *
     * @return the value of upload.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload.type
     *
     * @param type the value for upload.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload.save_address
     *
     * @return the value of upload.save_address
     *
     * @mbg.generated
     */
    public String getSaveAddress() {
        return saveAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload.save_address
     *
     * @param saveAddress the value for upload.save_address
     *
     * @mbg.generated
     */
    public void setSaveAddress(String saveAddress) {
        this.saveAddress = saveAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload.add_time
     *
     * @return the value of upload.add_time
     *
     * @mbg.generated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload.add_time
     *
     * @param addTime the value for upload.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload.update_time
     *
     * @return the value of upload.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload.update_time
     *
     * @param updateTime the value for upload.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload.deleted_id
     *
     * @return the value of upload.deleted_id
     *
     * @mbg.generated
     */
    public Integer getDeletedId() {
        return deletedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload.deleted_id
     *
     * @param deletedId the value for upload.deleted_id
     *
     * @mbg.generated
     */
    public void setDeletedId(Integer deletedId) {
        this.deletedId = deletedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", code=").append(code);
        sb.append(", size=").append(size);
        sb.append(", type=").append(type);
        sb.append(", saveAddress=").append(saveAddress);
        sb.append(", addTime=").append(addTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", deletedId=").append(deletedId);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Upload other = (Upload) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getSize() == null ? other.getSize() == null : this.getSize().equals(other.getSize()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getSaveAddress() == null ? other.getSaveAddress() == null : this.getSaveAddress().equals(other.getSaveAddress()))
            && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDeletedId() == null ? other.getDeletedId() == null : this.getDeletedId().equals(other.getDeletedId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getSize() == null) ? 0 : getSize().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getSaveAddress() == null) ? 0 : getSaveAddress().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDeletedId() == null) ? 0 : getDeletedId().hashCode());
        return result;
    }
}